version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jem-sam-practice"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m7m4c1215ldj"
s3_prefix = "jem-sam-practice"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
